### Signup
POST {{host}}/auth/signup
Content-Type: application/json

{
  "username": "test",
  "email": "test@example.com",
  "password": "test",
  "token": "abc"
}

### Login
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### User Info
GET {{host}}/auth/login


### Logout
POST {{host}}/auth/logout
Content-Type: application/json

### Root
GET {{host}}/
